config/routes.rb
Stomata::Application.routes.draw do
  
  root :to => 'posts#index'
  

  resources :posts, :only => [:index, :new, :create, :show]

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    Post.create(params[:post])
    redirect_to posts_path
  end

  def show
    post = Post.find(params[:id])
    render '_show', :locals => {:post => post}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stomata</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner header">
      <div class="container-fluid">
        <a class="brand" href="/"><%= ENV['APP_TITLE'] || 'Stomata' %></a>
      </div>
    </div>
  </div>
  
  <div class="container-fluid">
    <div class="row-fluid">
      <% if content_for?(:sidebar) %>
      <div class="row-fluid">
        <div class="span9 content">
          <%= yield %>
        </div>
        <div class="span3">
          <div class="well sidebar sidebar-nav">
            <%= yield :sidebar %>
          </div>
        </div>
      </div>
      <% else %>
        <div class="row-fluid">
          <div class="span12 content">
            <%= yield %>
          </div>
        </div>
      <% end %>
    </div>
  </div>    

</body>
</html>

app/views/posts/_show.html.erb
<div class="post">
  <h3><%= post.title %></h3>
  <div class="post-content"><%= post.content %></div>
</div>

app/views/posts/index.html.erb
<div class="actions">
  <%= link_to 'New Post', new_post_path %>
</div>

<div class="posts">
  <% @posts.each do |p| %>
    <%= render 'show', :post => p %>
  <% end %>
</div>

<% if @posts.size > 0 %>
  <% content_for(:sidebar) do -%>
    <ul class="nav nav-list">
    <% @posts.each do |p| %>
      <li><%= link_to p.title, p %></li>
    <% end %>
    </ul>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_for(@post, :html => {:class => 'new_post well'}) do |f| %>
  <%= f.label 'title' %>
  <%= f.text_field :title, :class => 'title' %>
  <br />

  <%= f.label 'content' %>
  <%= f.text_area :content, :class => 'content' %>
  <br />

  <button type="submit" class="btn">Submit</button>
<% end %>  